# Generated by Django 4.2.30 on 2026-05-23 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=50, verbose_name='Res kodi')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Jami og'irlik (kg)")),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami summa')),
                ('image', models.ImageField(upload_to='arrived_groups/', verbose_name='Yuklar guruhi rasmi')),
                ('payment_status', models.CharField(choices=[("To'lov kutilmoqda", "To'lov kutilmoqda"), ('Tasdiqlash jarayonida', 'Tasdiqlash jarayonida'), ("To'lov tasdiqlandi", "To'lov tasdiqlandi"), ("To'lov rad etildi", "To'lov rad etildi"), ('Topshirildi', 'Topshirildi')], default="To'lov kutilmoqda", max_length=30)),
                ('payment_check', models.ImageField(blank=True, null=True, upload_to='checks/')),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, choices=[('Punktda', 'Punktda olib ketish'), ('Pochta', 'Pochta orqali'), ('Taksi', 'Taksi orqali')], max_length=20, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan admin')),
                ('delivered_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_groups', to=settings.AUTH_USER_MODEL, verbose_name='Topshirgan admin')),
                ('selected_cargos', models.ManyToManyField(blank=True, related_name='selected_in_groups', to='cargo.cargo', verbose_name='Yuklarni tanlash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrived_groups', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi (UTS ID)')),
            ],
            options={
                'verbose_name': 'Punkitga qabul (Guruh)',
                'verbose_name_plural': 'Punkitga qabul',
            },
        ),
        migrations.CreateModel(
            name='DeliveryQueue',
            fields=[
            ],
            options={
                'verbose_name': 'Yukni topshirish navbati',
                'verbose_name_plural': 'Yukni topshirish navbati',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('warehouse.arrivedgroup',),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
            ],
            options={
                'verbose_name': "To'lov tekshiruvi",
                'verbose_name_plural': "To'lov tekshiruvlari",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('warehouse.arrivedgroup',),
        ),
    ]
