# Generated by Django 4.2.30 on 2026-06-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_arrivedgroup_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivedgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='arrived_groups/', verbose_name='Yuklar guruhi rasmi'),
        ),
        migrations.AlterField(
            model_name='arrivedgroup',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami summa (USD)'),
        ),
    ]
