# Generated by Django 5.1.5 on 2026-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('china_avia_phone', models.CharField(max_length=255, verbose_name='Xitoy (AVIA) telefon')),
                ('china_avia_address', models.TextField(verbose_name='Xitoy (AVIA) manzili')),
                ('china_avia_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Xitoy (AVIA) narxi ($)')),
                ('china_avia_term', models.CharField(max_length=100, verbose_name='Xitoy (AVIA) muddati (kun)')),
                ('china_auto_phone', models.CharField(max_length=255, verbose_name='Xitoy (AVTO) telefon')),
                ('china_auto_address', models.TextField(verbose_name='Xitoy (AVTO) manzili')),
                ('china_auto_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Xitoy (AVTO) narxi ($)')),
                ('china_auto_term', models.CharField(max_length=100, verbose_name='Xitoy (AVTO) muddati (kun)')),
                ('contact_telegram', models.CharField(max_length=255, verbose_name='Telegram link')),
                ('contact_instagram', models.CharField(max_length=255, verbose_name='Instagram link')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='Asosiy telefon')),
            ],
            options={
                'verbose_name': 'Ombor va Kontakt sozlamalari',
                'verbose_name_plural': 'Ombor va Kontakt sozlamalari',
            },
        ),
    ]
