# Generated by Django 4.2.30 on 2026-05-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_supportmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Versiya (masalan: 1.0.3)')),
                ('play_store_url', models.URLField(verbose_name='Play Store havolasi')),
                ('app_store_url', models.URLField(verbose_name='App Store havolasi')),
                ('is_force_update', models.BooleanField(default=True, verbose_name='Majburiy yangilanish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ilova versiyasi',
                'verbose_name_plural': 'Ilova versiyasi',
            },
        ),
    ]
