# Generated by Django 4.2.30 on 2026-06-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_appversion'),
        ('services', 'services_0002_dollar_rate'),
    ]

    operations = [
    ]
