# Generated by Django 4.2.30 on 2026-06-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_merge_0003_appversion_services_0002_dollar_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousesettings',
            name='dollar_rate',
        ),
        migrations.RemoveField(
            model_name='warehousesettings',
            name='dollar_rate_updated_at',
        ),
    ]
