# Generated by Django 4.2.30 on 2026-06-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_warehousesettings_dollar_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousesettings',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, default=12700, max_digits=10, verbose_name="Dollar kursi (so'm)"),
        ),
        migrations.AddField(
            model_name='warehousesettings',
            name='dollar_rate_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kurs oxirgi yangilangan vaqt'),
        ),
    ]
