# Generated by Django 4.2.30 on 2026-06-03 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_dashboard', models.BooleanField(default=True, verbose_name='Dashboard')),
                ('can_accounts', models.BooleanField(default=False, verbose_name='Foydalanuvchilar (OTP, Arizalar)')),
                ('can_warehouse', models.BooleanField(default=False, verbose_name='Warehouse')),
                ('can_cargo', models.BooleanField(default=False, verbose_name='Yuklar (Cargo)')),
                ('can_flights', models.BooleanField(default=False, verbose_name='Reyslar')),
                ('can_chat', models.BooleanField(default=False, verbose_name='Chat xabarlari')),
                ('can_calc', models.BooleanField(default=False, verbose_name='Kalkulator')),
                ('can_notifications', models.BooleanField(default=False, verbose_name='Bildirishnomalar')),
                ('can_unassigned', models.BooleanField(default=False, verbose_name='Kodsiz tovarlar')),
                ('can_videos', models.BooleanField(default=False, verbose_name='Video darslik')),
                ('can_settings', models.BooleanField(default=False, verbose_name='Sozlamalar')),
                ('can_add_admin', models.BooleanField(default=False, verbose_name="Admin qo'shish")),
                ('can_export', models.BooleanField(default=True, verbose_name='Excel export')),
                ('can_bulk_actions', models.BooleanField(default=True, verbose_name='Bulk amallar')),
                ('can_delete', models.BooleanField(default=False, verbose_name="O'chirish")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_permission', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
            ],
            options={
                'verbose_name': 'Admin ruxsati',
                'verbose_name_plural': 'Admin ruxsatlari',
            },
        ),
    ]
