# Generated by Django 4.2.30 on 2026-05-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
            ],
            options={
                'verbose_name': "Ro'yxatdan o'tish so'rovi",
                'verbose_name_plural': "Ro'yxatdan o'tish so'rovlari",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_back',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_front',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_note',
            field=models.TextField(blank=True, help_text="Qo'shimcha izoh", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('passport_blur', 'Pasport rasmi xira'), ('invalid_data', 'Ma’lumotlar xato'), ('fake_document', 'Hujjat haqiqiy emas'), ('other', 'Boshqa sabab')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
