# Generated by Django 6.0.1 on 2026-02-01 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_is_bot_active_remove_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='jshshir',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_series',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
