# Generated by Django 6.0.1 on 2026-02-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_otpcode_phone_remove_user_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
    ]
