# Generated by Django 4.2.30 on 2026-05-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Reys nomi')),
                ('warehouse_start', models.DateField(verbose_name='Ombor qabul boshi')),
                ('warehouse_end', models.DateField(verbose_name='Ombor qabul oxiri')),
                ('arrival_date', models.DateField(verbose_name='Yetib kelish sanasi')),
                ('status', models.CharField(choices=[('jarayonda', 'Jarayonda'), ('tranzit', 'Tranzit zonasida'), ('yetkazildi', 'Yetkazildi')], default='jarayonda', max_length=20, verbose_name='Holati')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reys',
                'verbose_name_plural': 'Reyslar',
                'ordering': ['-arrival_date'],
            },
        ),
    ]
