# Generated by Django 4.2.30 on 2026-05-23 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('notification_type', models.CharField(choices=[('Omborda', '📦 Omborda'), ("Yo'lda", "🚚 Yo'lda"), ('Punktda', '📍 Punktda'), ('Topshirildi', '✅ Topshirildi'), ('Kutilmoqda', '⏳ Kutilmoqda'), ('Umumiy', '📢 Umumiy')], default='Umumiy', max_length=20, verbose_name='Turi')),
                ('cargo_id', models.IntegerField(blank=True, null=True, verbose_name='Yuk ID')),
                ('track_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trek kodi')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuborilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
