# Generated by Django 4.2.30 on 2026-05-23 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnassignedCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code', models.CharField(max_length=100, unique=True, verbose_name='Trek kodi')),
                ('flight_name', models.CharField(max_length=100, verbose_name='Reys raqami')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kelgan sana')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Kodsiz tovar',
                'verbose_name_plural': 'Kodsiz tovarlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
