# Generated by Django 6.0.1 on 2026-02-01 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code', models.CharField(max_length=50, unique=True, verbose_name='Trek kod')),
                ('status', models.CharField(choices=[('Omborda', 'Omborda'), ("Yo'lda", "Yo'lda"), ('Punktda', 'Punktda'), ('Topshirildi', 'Topshirildi')], default='Omborda', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Oxirgi o'zgarish")),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Topshirilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuk ',
                'verbose_name_plural': 'Yuklar',
            },
        ),
    ]
