# Generated by Django 4.2.30 on 2026-05-23 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code', models.CharField(max_length=100, unique=True, verbose_name='Trek kod')),
                ('flight_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reys')),
                ('status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Omborda', 'Omborda'), ("Yo'lda", "Yo'lda"), ('Punktda', 'Punktda'), ('Topshirildi', 'Topshirildi')], default='Kutilmoqda', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Omborga kelgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yuk',
                'verbose_name_plural': 'Yuklar',
            },
        ),
    ]
