# Generated by Django 6.0.1 on 2026-02-01 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivedCargo',
            fields=[
            ],
            options={
                'verbose_name': '3. Punktga kelgan (Topshirish)',
                'verbose_name_plural': '3. Punktga kelgan (Topshirish)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.CreateModel(
            name='DeliveredCargo',
            fields=[
            ],
            options={
                'verbose_name': '4. Topshirilgan yuk',
                'verbose_name_plural': '4. Topshirilgan yuklar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.CreateModel(
            name='OnWayCargo',
            fields=[
            ],
            options={
                'verbose_name': "2. Yo'ldagi yuk",
                'verbose_name_plural': "2. Yo'ldagi yuklar",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.CreateModel(
            name='WarehouseCargo',
            fields=[
            ],
            options={
                'verbose_name': '1. Ombordagi yuk',
                'verbose_name_plural': '1. Ombordagi yuklar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cargos', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan admin"),
        ),
        migrations.AddField(
            model_name='cargo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cargos', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul admin"),
        ),
    ]
