# Generated by Django 4.2.30 on 2026-05-23 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='arrived_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='warehouse.arrivedgroup', verbose_name='Kelganlar guruhi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivered_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dl_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='onway_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ow_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cargos', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul admin"),
        ),
        migrations.AddField(
            model_name='cargo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='warehouse_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wh_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArrivedCargo',
            fields=[
            ],
            options={
                'verbose_name': 'Punkda (Topshirish)',
                'verbose_name_plural': 'Punktda (Topshirish)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.CreateModel(
            name='DeliveredCargo',
            fields=[
            ],
            options={
                'verbose_name': 'Topshirilgan yuk',
                'verbose_name_plural': 'Topshirilgan yuklar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.CreateModel(
            name='OnWayCargo',
            fields=[
            ],
            options={
                'verbose_name': "Yo'ldagi yuk",
                'verbose_name_plural': "Yo'ldagi yuklar",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.CreateModel(
            name='WarehouseCargo',
            fields=[
            ],
            options={
                'verbose_name': 'Ombordagi yuk',
                'verbose_name_plural': 'Ombordagi yuklar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
    ]
