# Generated by Django 4.2.30 on 2026-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('AVIA', 'AVIA'), ('AVTO', 'AVTO')], max_length=10, null=True, verbose_name='Transport turi'),
        ),
    ]
