# Generated by Django 5.1.5 on 2026-02-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_supportmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivedcargo',
            options={'verbose_name': '3. Punkda (Topshirish)', 'verbose_name_plural': '3. Punktda (Topshirish)'},
        ),
    ]
