# Generated by Django 5.1.5 on 2026-02-02 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_arrivedcargo_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='arrived_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrived_actions', to=settings.AUTH_USER_MODEL, verbose_name='Punktga qabul qilgan'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivered_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_actions', to=settings.AUTH_USER_MODEL, verbose_name='Topshirgan admin'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='onway_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onway_actions', to=settings.AUTH_USER_MODEL, verbose_name="Yo'lga chiqargan"),
        ),
        migrations.AddField(
            model_name='cargo',
            name='warehouse_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_actions', to=settings.AUTH_USER_MODEL, verbose_name='Ombor admini'),
        ),
    ]
