# Generated by Django 5.1.5 on 2026-02-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_cargo_arrived_admin_cargo_delivered_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('warehouse', 'Omborda'), ('on_way', "Yo'lda"), ('arrived', 'Punktda'), ('submitted', 'Topshirildi')], default='warehouse', max_length=20, verbose_name='Status'),
        ),
    ]
