# Generated by Django 5.1.5 on 2026-02-12 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_alter_cargo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='YouTube video havolasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='arrivedcargo',
            options={'verbose_name': 'Punkda (Topshirish)', 'verbose_name_plural': 'Punktda (Topshirish)'},
        ),
        migrations.AlterModelOptions(
            name='deliveredcargo',
            options={'verbose_name': 'Topshirilgan yuk', 'verbose_name_plural': 'Topshirilgan yuklar'},
        ),
        migrations.AlterModelOptions(
            name='onwaycargo',
            options={'verbose_name': "Yo'ldagi yuk", 'verbose_name_plural': "Yo'ldagi yuklar"},
        ),
        migrations.AlterModelOptions(
            name='warehousecargo',
            options={'verbose_name': 'Ombordagi yuk', 'verbose_name_plural': 'Ombordagi yuklar'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('Omborda', 'Omborda'), ("Yo'lda", "Yo'lda"), ('Punktda', 'Punktda'), ('Topshirildi', 'Topshirildi')], default='Omborda', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cargo_calc/')),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('is_responded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
